const fs = require('node:fs')
const path = require('node:path')
const { test } = require('node:test')

test('production desktop wiring exposes only the narrow main-process API', () => {
  const main = fs.readFileSync(path.join(__dirname, 'main.js'), 'utf8')
  const preload = fs.readFileSync(path.join(__dirname, 'preload.js'), 'utf8')
  const index = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8')
  const renderer = fs.readFileSync(path.join(__dirname, 'renderer.js'), 'utf8')

  require('node:assert/strict').match(main, /safeStorage/)
  require('node:assert/strict').match(main, /nodeIntegration:\s*false/)
  require('node:assert/strict').match(main, /api-login/)
  require('node:assert/strict').match(main, /hardenWindow/)
  require('node:assert/strict').match(main, /createApiHandlers/)
  require('node:assert/strict').match(main, /validateSettingsPatch/)
  require('node:assert/strict').match(main, /assertTrustedSender/)
  require('node:assert/strict').match(preload, /removeItem\('jws_token'\)/)
  require('node:assert/strict').match(preload, /createPreloadApi/)
  require('node:assert/strict').match(index, /<body class="needs-login">/)
  require('node:assert/strict').match(index, /login-controller\.js/)
  require('node:assert/strict').match(index, /chat-stream\.js/)
  require('node:assert/strict').doesNotMatch(index, /auth\.js/)
  require('node:assert/strict').doesNotMatch(renderer, /\bfetch\s*\(/)
  require('node:assert/strict').doesNotMatch(renderer, /jws_token|X-JWS-Token|access_token/)
  require('node:assert/strict').match(renderer, /needs-login/)
  require('node:assert/strict').match(renderer, /JWSLoginController/)
  require('node:assert/strict').match(renderer, /JWSChatStream/)
})
